export const ATTENDANCE = {
    HADIR:"HADIR",
    IZIN:"IZIN",
    TIDAK_HADIR:"TIDAK_HADIR",
    LIBUR:"LIBUR",
    CUTI : "CUTI"
}

export const CONTENT = {
    HOME:'HOME',
    EMPLOYEE_DATA : 'EMPLOYEE_DATA',
    EMPLOYEE_EDIT:"EMPLOYEE_EDIT",
    EMPLOYEE_DETAIL:"EMPLOYEE_DETAIL",
    ATTENDANCE : 'ATTENDANCE',
    ATTENDANCE_EDIT : "ATTENDANCE_EDIT",
    ATTENDANCE_DETAIL : 'ATTENDANCE_DETAIL',
    ATTENDANCE_APPROVAL : 'ATTENDANCE_APPROVAL',
    TEST: 'TEST',
}

export const ATTENDANCE_ACTION = {
    SET_STATUS : 'SET_STATUS', 
    UPDATE_DETAIL : 'UPDATE_DETAIL',
}

export const EMPLOYEE_ACTION = {
    ADD_EMPLOYEE : "ADD_EMPLOYEE",
    EDIT_EMPLOYEE : "EDIT_EMPLOYEE",
    DELETE_EMPLOYEE : "DELETE_EMPLOYEE",
}

    
export const url = {
    'ALL_EMPLOYEES' : 'http://localhost:3000/employees'
}
